server:
  # 服务器访问端口
  port: 8080
  # 访问的基础路径
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.138:3306/employees
    username: root
    password: 123456
    # 连接池
    dbcp2:
      initial-size: 5
      max-idle: 20
      min-idle: 5
      test-on-return: true
      validation-query: SELECT 1 FROM DUAL
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update